// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB5fkufdHDuOcPrxrwFTSy3P7FcgsZuTE0",
      authDomain: "flappy-bird-67fb0.firebaseapp.com",
      projectId: "flappy-bird-67fb0",
      storageBucket: "flappy-bird-67fb0.appspot.com",
      messagingSenderId: "1000525349680",
      appId: "1:1000525349680:web:41c5baa17cd274fc15bef5");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fkufdHDuOcPrxrwFTSy3P7FcgsZuTE0',
    appId: '1:1000525349680:android:578b31c6f103713515bef5',
    messagingSenderId: '1000525349680',
    projectId: 'flappy-bird-67fb0',
    storageBucket: 'flappy-bird-67fb0.appspot.com',
  );
}
